export const COMPONENTS = [
  { type: "user", label: "User", trustLevel: "External" },
  { type: "admin", label: "Admin", trustLevel: "Internal" },
  { type: "web-client", label: "Web Client", trustLevel: "External" },
  { type: "mobile-app", label: "Mobile App", trustLevel: "External" },
  { type: "api-gateway", label: "API Gateway", trustLevel: "Internal" },
  { type: "web-server", label: "Web Server", trustLevel: "DMZ" },
  { type: "app-server", label: "Application Server", trustLevel: "Internal" },
  { type: "database-sql", label: "Database (SQL)", trustLevel: "Restricted" },
  { type: "database-nosql", label: "Database (NoSQL)", trustLevel: "Restricted" },
  { type: "auth-server", label: "Authentication Server", trustLevel: "Internal" },
  { type: "external-api", label: "External API", trustLevel: "External" },
  { type: "third-party", label: "Third-Party Service", trustLevel: "External" },
  { type: "payment-gateway", label: "Payment Gateway", trustLevel: "External" },
  { type: "file-storage", label: "File Storage", trustLevel: "Internal" },
  { type: "message-queue", label: "Message Queue", trustLevel: "Internal" },
  { type: "microservice", label: "Internal Microservice", trustLevel: "Internal" },
  { type: "waf", label: "WAF", trustLevel: "DMZ" },
  { type: "firewall", label: "Firewall", trustLevel: "DMZ" },
  { type: "ids", label: "IDS", trustLevel: "Internal" },
  { type: "ips", label: "IPS", trustLevel: "Internal" },
  { type: "vpn-gateway", label: "VPN Gateway", trustLevel: "DMZ" },
  { type: "reverse-proxy", label: "Reverse Proxy", trustLevel: "DMZ" },
  { type: "mfa-server", label: "MFA Server", trustLevel: "Internal" },
  { type: "siem", label: "SIEM", trustLevel: "Internal" },
  { type: "load-balancer", label: "Load Balancer", trustLevel: "DMZ" },
];

const DEFAULT_NODE_DATA = {
  user: {
    label: "User",
    trustLevel: "External",
    requiresAuth: false,
    usesHTTPS: false,
    handlesSensitiveData: false,
    allowsFileUpload: false,
    externalInput: true,
    secureHeaders: false,
    debugMode: false,
  },
  admin: {
    label: "Admin",
    trustLevel: "Internal",
    requiresAuth: true,
    usesHTTPS: true,
    handlesSensitiveData: true,
    allowsFileUpload: false,
    externalInput: false,
    secureHeaders: true,
    debugMode: false,
  },
  "web-client": {
    label: "Web Client",
    trustLevel: "External",
    requiresAuth: false,
    usesHTTPS: false,
    handlesSensitiveData: false,
    allowsFileUpload: false,
    externalInput: true,
    secureHeaders: false,
    debugMode: false,
  },
  "mobile-app": {
    label: "Mobile App",
    trustLevel: "External",
    requiresAuth: false,
    usesHTTPS: false,
    handlesSensitiveData: false,
    allowsFileUpload: false,
    externalInput: true,
    secureHeaders: false,
    debugMode: false,
  },
  "api-gateway": {
    label: "API Gateway",
    trustLevel: "Internal",
    requiresAuth: true,
    usesHTTPS: true,
    handlesSensitiveData: true,
    allowsFileUpload: false,
    externalInput: true,
    secureHeaders: true,
    debugMode: false,
  },
  "web-server": {
    label: "Web Server",
    trustLevel: "DMZ",
    requiresAuth: true,
    usesHTTPS: true,
    handlesSensitiveData: false,
    allowsFileUpload: true,
    externalInput: true,
    secureHeaders: true,
    debugMode: false,
  },
  "app-server": {
    label: "Application Server",
    trustLevel: "Internal",
    requiresAuth: true,
    usesHTTPS: true,
    handlesSensitiveData: true,
    allowsFileUpload: true,
    externalInput: false,
    secureHeaders: true,
    debugMode: false,
  },
  "database-sql": {
    label: "Database (SQL)",
    trustLevel: "Restricted",
    requiresAuth: true,
    usesHTTPS: true,
    handlesSensitiveData: true,
    allowsFileUpload: false,
    externalInput: false,
    secureHeaders: true,
    debugMode: false,
  },
  "database-nosql": {
    label: "Database (NoSQL)",
    trustLevel: "Restricted",
    requiresAuth: true,
    usesHTTPS: true,
    handlesSensitiveData: true,
    allowsFileUpload: false,
    externalInput: false,
    secureHeaders: true,
    debugMode: false,
  },
  "auth-server": {
    label: "Authentication Server",
    trustLevel: "Internal",
    requiresAuth: true,
    usesHTTPS: true,
    handlesSensitiveData: true,
    allowsFileUpload: false,
    externalInput: false,
    secureHeaders: true,
    debugMode: false,
  },
  "external-api": {
    label: "External API",
    trustLevel: "External",
    requiresAuth: true,
    usesHTTPS: true,
    handlesSensitiveData: false,
    allowsFileUpload: false,
    externalInput: true,
    secureHeaders: false,
    debugMode: false,
  },
  "third-party": {
    label: "Third-Party Service",
    trustLevel: "External",
    requiresAuth: true,
    usesHTTPS: true,
    handlesSensitiveData: false,
    allowsFileUpload: false,
    externalInput: true,
    secureHeaders: false,
    debugMode: false,
  },
  "payment-gateway": {
    label: "Payment Gateway",
    trustLevel: "External",
    requiresAuth: true,
    usesHTTPS: true,
    handlesSensitiveData: true,
    allowsFileUpload: false,
    externalInput: true,
    secureHeaders: false,
    debugMode: false,
  },
  "file-storage": {
    label: "File Storage",
    trustLevel: "Internal",
    requiresAuth: true,
    usesHTTPS: true,
    handlesSensitiveData: true,
    allowsFileUpload: true,
    externalInput: false,
    secureHeaders: true,
    debugMode: false,
  },
  "message-queue": {
    label: "Message Queue",
    trustLevel: "Internal",
    requiresAuth: true,
    usesHTTPS: true,
    handlesSensitiveData: false,
    allowsFileUpload: false,
    externalInput: false,
    secureHeaders: true,
    debugMode: false,
  },
  microservice: {
    label: "Internal Microservice",
    trustLevel: "Internal",
    requiresAuth: true,
    usesHTTPS: true,
    handlesSensitiveData: true,
    allowsFileUpload: false,
    externalInput: false,
    secureHeaders: true,
    debugMode: false,
  },
  waf: {
    label: "WAF",
    trustLevel: "DMZ",
    requiresAuth: false,
    usesHTTPS: true,
    handlesSensitiveData: false,
    allowsFileUpload: false,
    externalInput: true,
    secureHeaders: true,
    debugMode: false,
  },
  firewall: {
    label: "Firewall",
    trustLevel: "DMZ",
    requiresAuth: false,
    usesHTTPS: true,
    handlesSensitiveData: false,
    allowsFileUpload: false,
    externalInput: true,
    secureHeaders: true,
    debugMode: false,
  },
  ids: {
    label: "IDS",
    trustLevel: "Internal",
    requiresAuth: false,
    usesHTTPS: true,
    handlesSensitiveData: false,
    allowsFileUpload: false,
    externalInput: false,
    secureHeaders: true,
    debugMode: false,
  },
  ips: {
    label: "IPS",
    trustLevel: "Internal",
    requiresAuth: false,
    usesHTTPS: true,
    handlesSensitiveData: false,
    allowsFileUpload: false,
    externalInput: false,
    secureHeaders: true,
    debugMode: false,
  },
  "vpn-gateway": {
    label: "VPN Gateway",
    trustLevel: "DMZ",
    requiresAuth: true,
    usesHTTPS: true,
    handlesSensitiveData: true,
    allowsFileUpload: false,
    externalInput: true,
    secureHeaders: true,
    debugMode: false,
  },
  "reverse-proxy": {
    label: "Reverse Proxy",
    trustLevel: "DMZ",
    requiresAuth: false,
    usesHTTPS: true,
    handlesSensitiveData: false,
    allowsFileUpload: false,
    externalInput: true,
    secureHeaders: true,
    debugMode: false,
  },
  "mfa-server": {
    label: "MFA Server",
    trustLevel: "Internal",
    requiresAuth: true,
    usesHTTPS: true,
    handlesSensitiveData: true,
    allowsFileUpload: false,
    externalInput: false,
    secureHeaders: true,
    debugMode: false,
  },
  siem: {
    label: "SIEM",
    trustLevel: "Internal",
    requiresAuth: false,
    usesHTTPS: true,
    handlesSensitiveData: false,
    allowsFileUpload: false,
    externalInput: false,
    secureHeaders: true,
    debugMode: false,
  },
  "load-balancer": {
    label: "Load Balancer",
    trustLevel: "DMZ",
    requiresAuth: false,
    usesHTTPS: true,
    handlesSensitiveData: false,
    allowsFileUpload: false,
    externalInput: true,
    secureHeaders: true,
    debugMode: false,
  },
};

const DEFAULT_EDGE_DATA = {
  encrypted: true,
  authenticated: true,
  externalInput: false,
  dataSensitivity: "Low",
  rateLimited: true,
  fileUpload: false,
  usesCookies: false,
  csrfProtected: true,
  sessionExpiryEnabled: true,
  secureCookies: true,
  deserializationValidated: true,
  corsAllowAll: false,
};

export const createNode = (type, position) => {
  const data = DEFAULT_NODE_DATA[type] || {
    label: "Component",
    trustLevel: "Internal",
    requiresAuth: false,
    usesHTTPS: false,
    handlesSensitiveData: false,
    allowsFileUpload: false,
    externalInput: false,
    secureHeaders: false,
    debugMode: false,
  };
  return {
    id: crypto.randomUUID(),
    type: "default",
    position,
    data: {
      componentType: type,
      ...data,
    },
  };
};

export const createEdge = (source, target) => ({
  id: crypto.randomUUID(),
  source,
  target,
  type: "smoothstep",
  data: {
    ...DEFAULT_EDGE_DATA,
  },
});

const layoutPosition = (index) => ({
  x: 120 + (index % 4) * 220,
  y: 80 + Math.floor(index / 4) * 160,
});

export const hydrateNode = (node, index = 0) => {
  const type = node?.type || node?.data?.componentType || "component";
  const defaults = DEFAULT_NODE_DATA[type] || DEFAULT_NODE_DATA.user;
  return {
    id: node?.id || crypto.randomUUID(),
    type: "default",
    position: node?.position || layoutPosition(index),
    data: {
      componentType: type,
      ...defaults,
      ...(node?.data || {}),
    },
  };
};

export const hydrateEdge = (edge) => ({
  id: edge?.id || crypto.randomUUID(),
  source: edge?.source,
  target: edge?.target,
  type: edge?.type || "smoothstep",
  data: {
    ...DEFAULT_EDGE_DATA,
    ...(edge?.data || {}),
  },
});
